-- Seed the initial asset types to migrate from the old hardcoded array
INSERT INTO asset_types (name, description, parameters_schema, is_active) VALUES
('Laptop', 'Laptop computers', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false},{"name":"Purchase Price (KSh)","type":"number","required":false},{"name":"Current Value (KSh)","type":"number","required":false},{"name":"RAM","type":"dropdown","options":"4GB, 8GB, 16GB, 32GB, 64GB","required":false},{"name":"Storage","type":"text","required":false},{"name":"Processor","type":"text","required":false},{"name":"OS","type":"text","required":false}]', 1),
('Desktop', 'Desktop computers', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false},{"name":"Purchase Price (KSh)","type":"number","required":false},{"name":"Current Value (KSh)","type":"number","required":false},{"name":"RAM","type":"dropdown","options":"4GB, 8GB, 16GB, 32GB, 64GB","required":false},{"name":"Storage","type":"text","required":false},{"name":"Processor","type":"text","required":false},{"name":"OS","type":"text","required":false}]', 1),
('Server', 'Server hardware', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false},{"name":"Purchase Price (KSh)","type":"number","required":false},{"name":"Current Value (KSh)","type":"number","required":false},{"name":"RAM","type":"dropdown","options":"16GB, 32GB, 64GB, 128GB, 256GB","required":false},{"name":"Storage","type":"text","required":false},{"name":"Processor","type":"text","required":false},{"name":"OS","type":"text","required":false}]', 1),
('Monitor', 'Display monitors', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false},{"name":"Purchase Price (KSh)","type":"number","required":false},{"name":"Current Value (KSh)","type":"number","required":false}]', 1),
('Keyboard', 'Keyboards', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false}]', 1),
('Mouse', 'Computer mice', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false}]', 1),
('Phone', 'Mobile phones', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Tablet', 'Tablet devices', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Printer', 'Printers and copiers', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Router', 'Network routers', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Switch', 'Network switches', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Projector', 'Display projectors', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1),
('Camera', 'Cameras and webcams', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false}]', 1),
('Furniture', 'Office furniture', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false}]', 1),
('Vehicle', 'Company vehicles', '[{"name":"Manufacturer","type":"global_dropdown","source":"manufacturer","required":false},{"name":"Category","type":"global_dropdown","source":"category","required":false},{"name":"Model","type":"text","required":false},{"name":"Serial Number","type":"text","required":false},{"name":"Status","type":"global_dropdown","source":"status","required":false},{"name":"Condition","type":"global_dropdown","source":"condition","required":false},{"name":"Purchase Date","type":"date","required":false},{"name":"Warranty End Date","type":"date","required":false}]', 1)
ON DUPLICATE KEY UPDATE
parameters_schema = VALUES(parameters_schema),
description = VALUES(description),
is_active = VALUES(is_active);
